version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/recipemate
    file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 60
      runas: ubuntu
    - location: scripts/stop.sh
      timeout: 60
      runas: ubuntu

  AfterInstall:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu
